# Generated by Django 3.2.8 on 2021-11-08 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20211107_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='category',
        ),
    ]
