# Generated by Django 3.2.8 on 2021-11-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_auto_20211107_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date_delate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
