# Generated by Django 3.2.8 on 2021-11-08 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_category_date_delate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_delate',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user_delete',
        ),
    ]
