# Generated by Django 3.2.8 on 2021-11-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_auto_20211108_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='derection',
            new_name='direction',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='descrption',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='sex',
        ),
        migrations.AddField(
            model_name='clients',
            name='description',
            field=models.TextField(default=1, verbose_name='Referencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=10, verbose_name='Sexo'),
        ),
    ]
