# Generated by Django 3.2.8 on 2021-11-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_auto_20211108_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='date_birth',
        ),
        migrations.AddField(
            model_name='clients',
            name='ruc',
            field=models.CharField(default='00000000000', max_length=11, verbose_name='Ruc'),
        ),
    ]
