# Generated by Django 3.2.8 on 2021-11-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_auto_20211108_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='employee',
        ),
    ]
