# Generated by Django 3.2.8 on 2021-11-17 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_alter_order_date_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order_detail',
            table=None,
        ),
    ]
