# Generated by Django 3.2.8 on 2021-11-19 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_alter_order_detail_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clients',
            table=None,
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
    ]
