# Generated by Django 3.2.8 on 2021-11-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_auto_20211118_2323'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clients',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='order',
            table='pedido',
        ),
        migrations.AlterModelTable(
            name='order_detail',
            table='Detalle_pedido',
        ),
    ]
