# Generated by Django 3.2.8 on 2021-11-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_auto_20211121_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
