# Generated by Django 3.2.8 on 2021-11-23 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_alter_order_date_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.clients'),
        ),
    ]
